---
#Cria banco de dados para o Moodle e um usuário de banco utilizando as variáveis presentes no main.yml da pasta Defaults
 
- name: Cria o banco de dados para o Moodle
  mysql_db: name={{ mysql_db }} state=present
   
- name: Cria um usuario de banco para o Moodle
  mysql_user:
    name={{ mysql_user }}
    password={{ mysql_password }}
    priv=*.*:ALL
